Fix shouldAcceptNewConnectionHandler compilation error
'bool' cannot be converted to 'BOOL' on my macOS/golang 1.16 and 1.17.3:

./socket.go:222:17: cannot convert
shouldAcceptNewConnectionHandlers[listenerPtr](conn) (type bool) to type
_Ctype_schar

Before this commit:
https://github.com/Code-Hex/vz/actions/runs/1573583923
After this commit:
https://github.com/Code-Hex/vz/actions/runs/1573636116