Retain error in newVZDiskImageStorageDeviceAttachment
If newVZDiskImageStorageDeviceAttachment:initWithURL returns an error, we need to
call `retain` on it, otherwise it will be freed when exiting from the
@autoreleasepool block.

This commit also adds a TestNonExistingImageStorageDeviceAttachment() test which is
crashing before this commit:

```
% go test
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x58da27582680 pc=0x19e33a5a0]

runtime stack:
runtime.throw({0x1003d4d7b?, 0x1003c3154?})
	/usr/local/go/src/runtime/panic.go:1047 +0x40 fp=0x16fb9f460 sp=0x16fb9f430 pc=0x1002964d0
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:819 +0x1e4 fp=0x16fb9f490 sp=0x16fb9f460 pc=0x1002ad3b4

goroutine 20 [syscall]:
runtime.cgocall(0x1003c3134, 0x14000044d98)
	/usr/local/go/src/runtime/cgocall.go:158 +0x54 fp=0x14000044d60 sp=0x14000044d20 pc=0x100263824
github.com/Code-Hex/vz/v2._Cfunc_convertNSError2Flat(0x6000027c2670)
	_cgo_gotypes.go:344 +0x3c fp=0x14000044d90 sp=0x14000044d60 pc=0x1003bfd7c
github.com/Code-Hex/vz/v2.newNSError.func1(0x100868a68?)
	/Users/teuf/dev/vz/objcutil.go:234 +0x48 fp=0x14000044df0 sp=0x14000044d90 pc=0x1003c0a18
github.com/Code-Hex/vz/v2.newNSError(0x6000027c2670)
	/Users/teuf/dev/vz/objcutil.go:234 +0x30 fp=0x14000044e80 sp=0x14000044df0 pc=0x1003c0890
github.com/Code-Hex/vz/v2.NewDiskImageStorageDeviceAttachment({0x1003cd6c5, 0x12}, 0x7d?)
	/Users/teuf/dev/vz/storage.go:65 +0x114 fp=0x14000044f10 sp=0x14000044e80 pc=0x1003c1104
github.com/Code-Hex/vz/v2.TestNonExistingImageStorageDeviceAttachment(0x140001071e0?)
	/Users/teuf/dev/vz/error_test.go:15 +0x30 fp=0x14000044f60 sp=0x14000044f10 pc=0x1003bfbf0
testing.tRunner(0x14000107520, 0x100475880)
	/usr/local/go/src/testing/testing.go:1446 +0x10c fp=0x14000044fb0 sp=0x14000044f60 pc=0x100320d6c
testing.(*T).Run.func1()
	/usr/local/go/src/testing/testing.go:1493 +0x2c fp=0x14000044fd0 sp=0x14000044fb0 pc=0x100321aac
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1165 +0x4 fp=0x14000044fd0 sp=0x14000044fd0 pc=0x1002c8494
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1493 +0x300
```